swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/monthlyactivity:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/monthlyactivity/{activityId}:
    get:
      security:
        - Bearer: []
      tags:
      - User Module
      summary: "Find activity by ID"
      description: "Returns a single activity"
      operationId: "getActivityById"
      parameters:
      - name: "activityId"
        in: "path"
        description: "ID of activity to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Activity"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "activity not found"
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Identifier:
    properties:
      id:
        type: string
        description: user id
  UserActivity:
    type: object
    properties:
      activityId:
        type: string
  Activity:
    type: "object"
    required:
    - "name"
    - "Date"
    properties:
      id:
        type: "integer"
        format: "int64"
      date:
        type: "string"
        format: date
        pattern: '^\d{4}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])$'
        example: 20190816
      name:
        type: "string"
        example: "Golden Sun Bakery"
      ammount:
        type: "number"
      Balance:
        type: "number"
      Description:
        type: "string" 
      Category:
        type: "string"
      Note:
        type: "string"  

    
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
LoginResponse:
    type: object
    properties:
      token:
        type: string
UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
